[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
# https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
ignore = ["W191", "E111", "E114", "E117", "D206", "D300", "Q000", "Q001", "Q002", "Q003", "COM812", "COM819", "ISC001", "ISC002", "E501"]

[tool.ruff.lint.pydocstyle]
convention = "pep257"
