#!/bin/sh

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

set -e

cd "$(dirname "$0")/.."
LOG_INFO="${0##*/} ==>"
echo "$LOG_INFO START <=="

script/test

echo "$LOG_INFO END <=="
