#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."
LOG_INFO="${0##*/} ==>"
echo "$LOG_INFO START <=="

script/update

echo "$LOG_INFO making sure the database is running..."
docker compose up -d

PA001_VIRTUAL_ENV="$PWD/venv"

if [ "$VIRTUAL_ENV" != "$PA001_VIRTUAL_ENV" ]; then
    echo "$LOG_INFO activating virtual environment..."
    # shellcheck source=/dev/null
    . "$PA001_VIRTUAL_ENV/bin/activate"
fi

trap 'echo' INT

echo "$LOG_INFO starting development server..."
./manage.py runserver

trap - INT

echo "$LOG_INFO END <=="
