#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."
LOG_INFO="${0##*/} ==>"
echo "$LOG_INFO START <=="

script/update

echo "$LOG_INFO END <=="
