#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."
LOG_INFO="${0##*/} ==>"
echo "$LOG_INFO START <=="

PA001_VIRTUAL_ENV="$PWD/venv"

if [ "$VIRTUAL_ENV" = "$PA001_VIRTUAL_ENV" ]; then
    echo "$LOG_INFO [INFO] $PA001_VIRTUAL_ENV is active, on errors execute \`deactivate\` first, then run me again"
fi

if [ -f ".git/hooks/pre-commit" ]; then
    echo "$LOG_INFO Removing .git/hooks/pre-commit..."
    rm .git/hooks/pre-commit
fi

if [ -d "node_modules" ]; then
    echo "$LOG_INFO Removing node_modules..."
    rm -R node_modules
fi

if [ -d "$PA001_VIRTUAL_ENV" ]; then
    echo "$LOG_INFO Removing venv..."
    rm -R "$PA001_VIRTUAL_ENV"
fi

script/bootstrap

echo "$LOG_INFO END <=="
