#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."
LOG_INFO="${0##*/} ==>"
echo "$LOG_INFO START <=="

if [ -f ".git/hooks/pre-commit" ]; then
    echo "$LOG_INFO Removing .git/hooks/pre-commit..."
    rm .git/hooks/pre-commit
fi

if [ -d "node_modules" ]; then
    echo "$LOG_INFO Removing node_modules..."
    rm -R node_modules
fi

script/bootstrap

echo "$LOG_INFO END <=="
